--- luci-app-ssr-plus/Makefile
+++ luci-app-ssr-plus/Makefile
@@ -33,6 +33,13 @@ LUCI_DEPENDS:= \
 	+libuci-lua +lua +luci-compat +coreutils +coreutils-base64 +dns2tcp +dnsmasq-full \
 	+jq +ip-full +lua-neturl +libuci-lua +microsocks +ipt2socks +lyaml \
 	+resolveip +bind-dig +curl +nping +unzip +xz-utils +xz \
+	+PACKAGE_$(PKG_NAME)_INCLUDE_Xray:xray-core \
+	+PACKAGE_$(PKG_NAME)_INCLUDE_Xray:coreutils-timeout \
+	+PACKAGE_$(PKG_NAME)_INCLUDE_Http_Proxy:3proxy \
+	+PACKAGE_$(PKG_NAME)_INCLUDE_Mihomo:mihomo \
+	+PACKAGE_$(PKG_NAME)_INCLUDE_Mihomo:v2ray-geoip \
+	+PACKAGE_$(PKG_NAME)_INCLUDE_GeoData:v2ray-geoip \
+	+PACKAGE_$(PKG_NAME)_INCLUDE_GeoData:v2ray-geosite \
 	+PACKAGE_$(PKG_NAME)_INCLUDE_ChinaDNS_NG:chinadns-ng \
 	+PACKAGE_$(PKG_NAME)_INCLUDE_MosDNS:mosdns \
 	+PACKAGE_$(PKG_NAME)_INCLUDE_Shadow_TLS:shadow-tls \
